### PR TITLE
Check api

### PR DESCRIPTION
**Pull request by postgred**
Custom resource `graylog2_check_api ` for checking API.

Properties:
* uri -- API endpoint
* token -- User's authorization token

Example:
```
graylog2_check_api 'http://127.0.0.1:9000/api' do
    token: '2318530845fhls'
end
```

### CODE REVIEW

**Comment by mariussturm** [comment]
Hi,
I think there is something wrong, all the commits from your former PR are also included in this PR. Could you try to clean that up?

**Comment by postgred** [comment]
Hi. Yes, I think I can clean that.c

**Comment by postgred** [comment]
Done.

**Comment by mariussturm** [comment]
LGTM!

**Pull request merged**
