### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jjasghar**
Added the build badge per the new Chef Partner cookbook guide guidelines.

### CODE REVIEW

**Comment by mariussturm** [comment]
Thanks!

**Comment by joschi** [comment]
@jjasghar It looks like the Jenkins instance is failing to fetch the Git repository (https://jenkins-01.eastus.cloudapp.azure.com/job/graylog2-cookbook/131/console):

> ```
FATAL: org.eclipse.jgit.revwalk.RevWalk.close()V
java.lang.NoSuchMethodError: org.eclipse.jgit.revwalk.RevWalk.close()V
	at hudson.plugins.git.util.GitUtils$1.invoke(GitUtils.java:188)
	at hudson.plugins.git.util.GitUtils$1.invoke(GitUtils.java:143)
	at org.jenkinsci.plugins.gitclient.AbstractGitAPIImpl.withRepository(AbstractGitAPIImpl.java:28)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.withRepository(CliGitAPIImpl.java:63)
	at hudson.plugins.git.util.GitUtils.filterTipBranches(GitUtils.java:143)
	at hudson.plugins.git.util.DefaultBuildChooser.getAdvancedCandidateRevisions(DefaultBuildChooser.java:249)
	at hudson.plugins.git.util.DefaultBuildChooser.getCandidateRevisions(DefaultBuildChooser.java:53)
	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:980)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1083)
	at hudson.scm.SCM.checkout(SCM.java:495)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1278)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1720)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
```

Is there anything you can do about it?

**Comment by jjasghar** [comment]
Yep, we are working on it now. Updates when i get them. It's nice to see people are looking at the builds :)

**Comment by jjasghar** [comment]
@joschi looks like we're good now. Can you take care of the deprecation notifications?

**Comment by mariussturm** [comment]
@jjasghar I think the deprecations are not the reason for the failed build. This looks more like the origin: `Message: Could not load the 'azurerm' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.`
Do we need a special Gem for the Azure build?

**Comment by jjasghar** [comment]
Yeah i sent the email just a tad bit too early.

The `kitchen-azurerm` driver has been installed, and its running in my console now. :)

Everything should be set up correctly now.

**Pull request merged**
