### PR TITLE
Rewrite collector to use packages when possible

### PR DESCRIPTION
**Pull request by evanccnyc**
Fall back to manual install if no package is available

### CODE REVIEW

**Comment by mariussturm** [comment]
Thanks for the PR!
I think the `platform_version` logic doesn't work as intended. When you try to apply the recipe e.g.  on an older version of CentOS or Debian, only the very last `template` resource is executed.
Could you please also run:

```
bundle install
bundle exec rubocop recipes/collector.rb
```

And fix the syntax warnings to follow the coding standards?

**Comment by evanccnyc** [comment]
@mariussturm odd. what is the older versions of debian/centos reporting for platform?


Ill also run the bundle stuff shortly.

**Comment by mariussturm** [comment]
For example CentOS-6 with `kitchen converge default-centos-67`. The `case` statement is exited because only version 7 packages are available. After that there is only the `template '/etc/graylog/collector/collector.conf'` resource left.

So Debian 7 or CentOS 6 would jump directly to this point: https://github.com/evanccnyc/graylog2-cookbook/blob/e12c455f6a87ad3e8c4f75945b48e5ce21ea82cc/recipes/collector.rb#L160

But I think you wanted to do something like: if platform and version is ok -> use the system package. if not use the old installation way. This needs some rework of the case statement.

**Comment by evanccnyc** [comment]
Ah duh. Sorry Ill fix that and get a new PR this afternoon.

**Comment by evanccnyc** [comment]
@mariussturm okay should be fixed (also fixed the syntax issues). I must have been spacing on Friday.

**Comment by mariussturm** [comment]
Thanks! Great work.

**Pull request merged**
