### PR TITLE
Add customize data bag item

### PR DESCRIPTION
**Pull request by scopenco**
I have several Graylog instances for the different environments and I want to have one common data bag where i will have several items. This PR introduces the additional option for this and doesn't break compatibility with the previous version.

### CODE REVIEW

**Comment by mariussturm** [comment]
@scopenco thanks for the PR. Looks good to me, would you please sign the CLA so that I can merge this?

**Comment by scopenco** [comment]
done

**Comment by scopenco** [comment]
In addition, data_bag_item resources supports encrypted data bags too. What do you think i i'll change Chef::EncryptedDataBagItem.load to  data_bag_item? This will be better user frendly for testing cookbook and more flexible.

**Comment by mariussturm** [comment]
If the default stays compatible with the current data bag handling you can change the encrypted data bags as well. sure.

**Comment by scopenco** [comment]
yes right. Done

**Comment by scopenco** [comment]
Can you release new patch version to the supermarket?

**Comment by mariussturm** [comment]
done!

**Pull request merged**
